export const NTN_USER_REQUEST = "NTN_USER_REQUEST";
export const NTN_USER_SUCCESS = "NTN_USER_SUCCESS";
export const NTN_USER_FAIL = "NTN_USER_FAIL";
export const NTN_USER_RESET = "NTN_USER_RESET";

export const APPLICATIONS_REQUEST = "APPLICATIONS_REQUEST";
export const APPLICATIONS_SUCCESS = "APPLICATIONS_SUCCESS";
export const APPLICATIONS_FAIL = "APPLICATIONS_FAIL";
export const APPLICATIONS_RESET = "APPLICATIONS_RESET";

export const ROLES_REQUEST = "ROLES_REQUEST";
export const ROLES_SUCCESS = "ROLES_SUCCESS";
export const ROLES_FAIL = "ROLES_FAIL";
export const ROLES_RESET = "ROLES_RESET";

export const LOCATION_REQUEST = "LOCATION_REQUEST";
export const LOCATION_SUCCESS = "LOCATION_SUCCESS";
export const LOCATION_FAIL = "LOCATION_FAIL";
export const LOCATION_RESET = "LOCATION_RESET";

export const APPLICATION_DETAILS_REQUEST = "APPLICATION_DETAILS_REQUEST";
export const APPLICATION_DETAILS_SUCCESS = "APPLICATION_DETAILS_SUCCESS";
export const APPLICATION_DETAILS_FAIL = "APPLICATION_DETAILS_FAIL";
export const APPLICATION_DETAILS_RESET = "APPLICATION_DETAILS_RESET";

export const APPLICATION_USER_CREATE_REQUEST = "APPLICATION_USER_CREATE_REQUEST";
export const APPLICATION_USER_CREATE_SUCCESS = "APPLICATION_USER_CREATE_SUCCESS";
export const APPLICATION_USER_CREATE_FAIL = "APPLICATION_USER_CREATE_FAIL";
export const APPLICATION_USER_CREATE_RESET = "APPLICATION_USER_CREATE_RESET";

export const APPLICATION_STATUS_REQUEST = "APPLICATION_STATUS_REQUEST";
export const APPLICATION_STATUS_SUCCESS = "APPLICATION_STATUS_SUCCESS";
export const APPLICATION_STATUS_FAIL = "APPLICATION_STATUS_FAIL";
export const APPLICATION_STATUS_RESET = "APPLICATION_STATUS_RESET";